name 'home_db'
maintainer 'Tim Beeler'
maintainer_email 'timothybeeler@me.com'
license 'all_rights'
description 'Installs/Configures home_db'
long_description 'Installs/Configures home_db'
version '0.0.1'
